### ISSUE TITLE
Regarding Background color

### ISSUE THREAD

**Issue by shubhamsamrat52** [Edwardsoen/Leetcode-Premium-Unlocker#1]
when we click on companies on leetcode then whole companies name appears which Background is black which results i can't see the data which is written. Please change the background color to any light color.

**Comment by Edwardsoen** [comment]
Hi, what browser are you using? do you use the site in light mode or dark mode? can you try to click any "Top company (facebook, google, or microsoft) Problems" and see if you face the same issue? and a screenshot would be great

**Comment by Edwardsoen** [comment]
should be fixed in 0.4.1
