### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by harsh-rajpal** [Edwardsoen/Leetcode-Premium-Unlocker#12]
The extension has stopped working. Tried updating and installing again but still its the same.

**Comment by Rik2907** [comment]
Yes now its not even showing the company tags in every question

**Comment by Edwardsoen** [comment]
yup confirmed, they made some changes in their website and it broke most of the extension's functionality. Currently working on a fix

**Comment by Edwardsoen** [comment]
closing for duplicate issue, checkout this thread for latest update https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/10
