### ISSUE TITLE
List of companies popup button does not show when leetcode is zoomed to more than 100%. 

### ISSUE THREAD

**Issue by adj2908** [Edwardsoen/Leetcode-Premium-Unlocker#16]
Hi,

I am using leetcode on chrome on MacOs. The extension fails to show the button when leetcode is zoomed to more than 110%. When page is zoomed to 100% the extension shows up. I have attached a screen recording of the same. 

Please fix this issue. Thanks for your effort. 
[leetcode.webm](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/18600164/0e0c6767-38d0-4af2-bef0-2fb7e0a940c0)

**Comment by Edwardsoen** [comment]
confirmed and replicable, will fix next patch

**Comment by adj2908** [comment]
@Edwardsoen. When can we expect a fix for this? Thanks.

**Comment by adj2908** [comment]
Sure thanks.

**Comment by Edwardsoen** [comment]
Fixed in latest update 0.5.4
