### ISSUE TITLE
Cannot view locked content. It asks for subscription

### ISSUE THREAD

**Issue by harikarthiks** [Edwardsoen/Leetcode-Premium-Unlocker#18]

**Comment by Edwardsoen** [comment]
Which page? which content? which browser?

**Comment by smith558** [comment]
@Edwardsoen I think he might be talking about editorials, those are still locked
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/44023416/29416756-5abb-4573-8873-3a93a0386058)

**Comment by Edwardsoen** [comment]
Duplicate issue https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/20 
closing this thread
