### ISSUE TITLE
Typo Error in extension tooltip

### ISSUE THREAD

**Issue by shubham-mishra-ca** [Edwardsoen/Leetcode-Premium-Unlocker#19]
It's a low priority bug but I happen to come across while I was browsing the extension. 

Attached photo for reference.

![bug](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/53086327/a9f4f675-838f-4c2d-aff7-951eebfb1338)

**Comment by Edwardsoen** [comment]
nice catch,  it is fixed.
