### ISSUE TITLE
 LeetCode Curated SQL 70

### ISSUE THREAD

**Issue by VellalaVineethKumar** [Edwardsoen/Leetcode-Premium-Unlocker#2]
Hi Edwardsoen,
first of all, you are doing a great job! love your work!
Theres a small issue, i cant see the premiun questions of LeetCode Curated SQL 70 from the main page.
PFA screenshot attached
![image](https://user-images.githubusercontent.com/31627944/226092776-a2f590a2-7a1a-46f4-a368-4f1c9a8cd10d.png)

**Comment by VellalaVineethKumar** [comment]
After clicking on LeetCode Curated SQL 70
![image](https://user-images.githubusercontent.com/31627944/226092840-53260606-eba6-42b0-87a1-1b647fc299a1.png)

**Comment by Edwardsoen** [comment]
Hi, premium question unlocking is still not supported as of now (still working on it), but the frequency progress bar should be unlocked in Curated SQL 70 page. Let me know if it doesnt for you. 
And i just noticed premium Featured Lists button is not unlocked on Featured Lists page, so thanks for bringing this up
