### ISSUE TITLE
the extension is not working neither on chrome nor on brave

### ISSUE THREAD

**Issue by aksharaian** [Edwardsoen/Leetcode-Premium-Unlocker#21]

**Comment by Edwardsoen** [comment]
Hi, which part isnt working? any screenshots? any error log?

**Comment by aksharaian** [comment]
It's working now, thanks

**Comment by Edwardsoen** [comment]
If this extension got removed from chrome store you can still download the zip file from Github and load it manually. 

if you want to save the data you can simply duplicate this <a href = "https://docs.google.com/spreadsheets/d/1hW-bfeFKSkEDzfjaDMjDQmgsupEZz3gysXpG0mrf6QE/edit#gid=1555553759"> sheet</a>. This sheet literally serve as the 'backend' of this app

**Comment by aksharaian** [comment]
Thank you for your help!
Super cool extension 🫶
