### ISSUE TITLE
Could not able to see javascript premium questions

### ISSUE THREAD

**Issue by vkaswin** [Edwardsoen/Leetcode-Premium-Unlocker#23]

**Comment by Edwardsoen** [comment]
any screenshots?

**Comment by vkaswin** [comment]
![Screenshot from 2023-06-22 12-26-54](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/71980333/978c5813-40d5-4113-ad64-685a31725611)
Showing No data when select any javascript premium questions

**Comment by Edwardsoen** [comment]
Oh, this is newly added questions, i dont have data for this questions yet. questions with id > 2500 are new

**Comment by vkaswin** [comment]
Okay
