### ISSUE TITLE
Extension is not working in Leetcode Study Plan

### ISSUE THREAD

**Issue by rahul4tripathi2** [Edwardsoen/Leetcode-Premium-Unlocker#25]
Hi,

I am trying to explore Binary Search study plan but for some of problem it is still not unlocking premium features

https://leetcode.com/studyplan/binary-search/

![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/20778899/8561c995-84e3-4e66-8e9d-1caf6b4aa519)

**Comment by Edwardsoen** [comment]
Hi, study plan unlocking is currently not supported, will update here https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/17, closing this issue.
