### ISSUE TITLE
Cannot view locked content

### ISSUE THREAD

**Issue by Akshatchaube01** [Edwardsoen/Leetcode-Premium-Unlocker#27]
The extension isn't working, it just keeps loading the page, please get it fixed . Thankyou 
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/92796050/d11c0023-254d-4ed1-81ba-d453a2760cb6)

**Comment by Edwardsoen** [comment]
Try again and let me know if you still face the same issue.

**Comment by md-front** [comment]
@Edwardsoen  Looks like I have the same issue

![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/23565573/afad01af-b888-462c-94e0-a69a6cad88f4)

**Comment by Edwardsoen** [comment]
> 

this is not a bug, i have added the data but this feature is not up yet

**Comment by Akshatchaube01** [comment]
It is working now ! Thanks a lot
