### ISSUE TITLE
Leads to subscription page, whenever I click any company name

### ISSUE THREAD

**Issue by para8ox-deb** [Edwardsoen/Leetcode-Premium-Unlocker#28]
Whenever I click on google, amazon or any company it leads me to the subscription page.

![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/50060952/a22d0d7f-5844-4dd0-ba79-771c60dc474e)

**Comment by Edwardsoen** [comment]
where do you click it from ? which browser ?

**Comment by harshil-eth** [comment]
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/75800986/fa2b5039-af1d-4c26-9865-e145c20e669c)

Not allowing me to see companies list

**Comment by Edwardsoen** [comment]
Issue fixed in 0.5.4
