### ISSUE TITLE
Companies button is not visible

### ISSUE THREAD

**Issue by adj2908** [Edwardsoen/Leetcode-Premium-Unlocker#29]
Hi,

I am not able to see the companies tag green button(Attached the below screenshot). Can you please look into this? Thanks for your effort.

![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/18600164/cd7efefb-4c77-4916-818e-146c797a2aa6)

**Comment by chamakurib** [comment]
+1

Issue started approximately around 18 July 10pm IST.
@Edwardsoen Can you please take a look?

**Comment by Edwardsoen** [comment]
issue confirmed, i will take a look tonight

**Comment by AliHannoura** [comment]
Any updates? Was it disabled by leetCode? Or just some problem?

**Comment by Rik2907** [comment]
is there any update?

**Comment by Edwardsoen** [comment]
fixed in v0.5.5, please wait a few days until chrome store review is approved and update your extension.

**Comment by adj2908** [comment]
Is there a way we can use this without waiting for approval from chrome store review?

**Comment by Edwardsoen** [comment]
> @Edwardsoen Is there a way we can use this without waiting for approval from chrome store review?

its already approved, please update your extension. Or you can download in github 'release' tab and load it manually. 
let me know if you still face any issues
