### ISSUE TITLE
Does not seem to work, is it because I am using ChromeOS?

### ISSUE THREAD

**Issue by maharshiuprit** [Edwardsoen/Leetcode-Premium-Unlocker#31]
Hi I recently downloaded the extension, tried refreshing logging in and logging out, etc. However the website remains unchanged, is there something I am doing wrong? Could my ChromeOS be the problem?

**Comment by Edwardsoen** [comment]
The browser should matter more than the operating system, any screenshots ?

**Comment by Edwardsoen** [comment]
looks like you are using old ui ? try to switch to new ui

**Comment by maharshiuprit** [comment]
Works thanks!
