### ISSUE TITLE
Study plan does not open

### ISSUE THREAD

**Issue by Ancoco** [Edwardsoen/Leetcode-Premium-Unlocker#32]
I tried opening sprint interview questions and it still says to subscribe. I have also tried to open **premium algo 100** but still unable to open it.
<img width="879" alt="problem" src="https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/88350684/ff083bb7-9542-44a5-9d36-e81ef7e40522">

**Comment by Edwardsoen** [comment]
study plan unlocking is not supported for now, check out this issue. https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/17
