### ISSUE TITLE
Video Solution 

### ISSUE THREAD

**Issue by Anubhab2003** [Edwardsoen/Leetcode-Premium-Unlocker#34]
It would be really helpful if we could access the Video Solution using the extension.
All though all the other premium feature are accessible.
Would like to Appreciate the work and effort Developers have put in.
Hope a positive Response.
![Screenshot 2023-08-13 114250](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/99398916/0aaf4a91-3ca7-4e4f-8dd8-76f8e1374b53)

**Comment by Edwardsoen** [comment]
editorial unlocking is on the way， closing for duplicate issue https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/26
