### ISSUE TITLE
Still cannot access few question

### ISSUE THREAD

**Issue by Anubhab2003** [Edwardsoen/Leetcode-Premium-Unlocker#36]
![Screenshot 2023-08-14 195219](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/99398916/589aaa01-95f5-432f-adda-b9e1344c0797)

**Comment by Edwardsoen** [comment]
not a bug, you can only access premium question via front page (check out https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/20)
