### ISSUE TITLE
Can't click on Editorials tab after update that introduced unlocking of editorials

### ISSUE THREAD

**Issue by Aadityakiran-S** [Edwardsoen/Leetcode-Premium-Unlocker#39]
After the update that included unlocking the editorials section, the tab to click on the actual editorial window is not working. Cannot click on editorials tab even if it's free. Have to go to the URL and change the string after the last slash to go to the editorials section.

**Comment by Edwardsoen** [comment]
Problem replicable, i am reverting editorial unlocking feature in v0.6.6 until i found a fix.
