### ISSUE TITLE
Cannot see companies list when clicked on companies button

### ISSUE THREAD

**Issue by Parag18081994** [Edwardsoen/Leetcode-Premium-Unlocker#4]
When i open a specific problem, I am not able to see list of companies after click on companies icon in which that specific problem was asked but when I open the list of problem I am able to see frequency, list of problem specific to companies. This issue has been observed since today.

**Comment by Edwardsoen** [comment]
Hi, do you have screenshot? which browser you are using?

**Comment by Parag18081994** [comment]
Hi,

I am using a Firefox browser.

Below is the screenshot.

[image: image.png]

Thanks and Regards,
Parag Naik

**Comment by Edwardsoen** [comment]
i cannot see your attached image, not sure if you can reply image via email 😅

**Comment by ShardulPrabhu** [comment]
> Hi, I am using a Firefox browser. Below is the screenshot. [image: image.png] Thanks and Regards, Parag Naik
> […](#)

If the new screen is not visible, please click on the 'new' button located in the bottom right corner of the screen.

**Comment by Parag18081994** [comment]
![leetcode](https://user-images.githubusercontent.com/66076965/232516176-5e2d4c25-bda9-4d8d-a910-eee7e0119b52.JPG)

**Comment by Parag18081994** [comment]
Well I discovered something else too when I try to drag and reduce the code editor size, the plugin is working perfectly.

**Comment by Edwardsoen** [comment]
looks like this line of code is causing the issue 
https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/blob/4c519923505fc368aae60f6dca5b06e20c9ac74e/src/modules/ElementModifier/ProblemTagsElementModifier.js#L41
when reduce the width of the left page the lock logo in "Editorial" tab is hidden, causing unexpected behavior. 
For now make sure the left page is wide enough that the lock logo in "Editorial" tab is not hidden.
