### ISSUE TITLE
Frequency not working in the tag section.

### ISSUE THREAD

**Issue by happy-t** [Edwardsoen/Leetcode-Premium-Unlocker#41]
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/63543719/21fbbc00-c433-4e00-bff2-3d03c6262223)

**Comment by Edwardsoen** [comment]
closing for duplicate issue https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/24
