### ISSUE TITLE
All features seem to have stopped working (?) very recently

### ISSUE THREAD

**Issue by VKohli17** [Edwardsoen/Leetcode-Premium-Unlocker#43]
Was working alright a few hours ago, now frequency's hidden and the popup upon clicking a company tag stays spinning forever.

![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/66561036/8a8260c4-fac4-4ed0-be16-e2b7f84b1c02)

Does this have something to do with the raw data google sheet being deleted?

**Comment by Edwardsoen** [comment]
oh yeah, the google sheets serve as the 'backend' of this app. So yeah that's the cause. Not sure why suddenly it got deleted. 
Will update very soon.

**Comment by Edwardsoen** [comment]
I have updated the extension, please wait until it get approved

**Comment by Edwardsoen** [comment]
> 

yea will do that later

**Comment by Edwardsoen** [comment]
latest patch is up, please update your extension
