### ISSUE TITLE
FireFox is not working

### ISSUE THREAD

**Issue by Rajesh4c2** [Edwardsoen/Leetcode-Premium-Unlocker#45]
upto yesterday i get editorials but now it's just loading not working properly

**Comment by Edwardsoen** [comment]
Fixed in 0.6.7, please update your extension

**Comment by Rajesh4c2** [comment]
bro after extension to 0.6.7 editorials are not opening.

**Comment by Edwardsoen** [comment]
Editorials unlocking is disabled temporarily as it is causing some problem, check out this issue https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/39
