### ISSUE TITLE
Cannot view problems by companies

### ISSUE THREAD

**Issue by husainsyed** [Edwardsoen/Leetcode-Premium-Unlocker#5]
![image](https://user-images.githubusercontent.com/40645497/233937563-65101263-fdb0-4aaa-b7ca-b99b9e9734ee.png)

Upon clicking, takes to LC premium page.

Page: https://leetcode.com/problemset/all/
Widget location: On the right-hand side.

**Comment by Edwardsoen** [comment]
Hi, what browser are you using? is the issue limited to company problem? does the frequency unlocking works?

**Comment by husainsyed** [comment]
using edge chromium. the frequency works just fine.

**Comment by Edwardsoen** [comment]
spent 30 mins cannot replicate the issue, will keep this open for now

**Comment by adj2908** [comment]
On chrome MacOs also it is not working. Not able to see the green button which shows the company frequency list.

**Comment by Edwardsoen** [comment]
> @Edwardsoen On chrome MacOs also it is not working. Not able to see the green button which shows the company frequency list.

Hi, can you provide screenshots? is the console showing any error logs?

**Comment by adj2908** [comment]
![image](https://user-images.githubusercontent.com/18600164/235213411-01ccfaab-d335-4d20-986e-b6e9f1ae542e.png)
Screenshot with console errors.

**Comment by Edwardsoen** [comment]
> 

oh this is the same issue as this https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/6 , it's because leetcode update their UI a bit, i patch it on v0.5.2 just now. Its up on firefox add-on store, chrome store review will take a few days

**Comment by husainsyed** [comment]
For me, a browser extension was switching my user-agent without notifying me. It was set to **MacOS**. When I switched it back to default, the extension works as it should. I'll still leave the issue open tho.
