### ISSUE TITLE
Playground not loading for LeetCode 64: Minimum Path Sum

### ISSUE THREAD

**Issue by Aadityakiran-S** [Edwardsoen/Leetcode-Premium-Unlocker#53]
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/75132386/4a899fe8-6c7c-46bc-8c64-964a400c1932)

It's working okay for other problems I've tried.

**Comment by Edwardsoen** [comment]
Hi, There is nothing much i can do if they remove it.
