### ISSUE TITLE
Company Name is not getting displayed in the question

### ISSUE THREAD

**Issue by lovepreet-kaur12** [Edwardsoen/Leetcode-Premium-Unlocker#57]
In any question, not able to see the compaines tag
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/22641982/8e65d8ab-5fd4-42f5-84b7-3131c5448e8a)

**Comment by Edwardsoen** [comment]
try new UI, the extension doesnt support old leetocode UI
