### ISSUE TITLE
Dead spreadsheet link

### ISSUE THREAD

**Issue by alina-cai** [Edwardsoen/Leetcode-Premium-Unlocker#58]
The raw data spreadsheet link in the README does not work

**Comment by alina-cai** [comment]
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/117325741/2694aea2-fc6f-4838-97e4-69c99876e96b)

**Comment by Edwardsoen** [comment]
Fixed in https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/pull/59
