### ISSUE TITLE
Leetcode updated the UI ,the companies button that appears in green is no longer visible

### ISSUE THREAD

**Issue by N7-BLACKHAT** [Edwardsoen/Leetcode-Premium-Unlocker#6]
![leetco-bug](https://user-images.githubusercontent.com/78254458/235062091-1fe06a4c-f674-4c5e-ab6f-02405b9b8af3.png)
upon clicking companies it takes to
![leetco-bug2](https://user-images.githubusercontent.com/78254458/235062195-702f2cdf-a095-418f-a90a-405df7b566c6.png)

**Comment by Parag18081994** [comment]
Its not working in Firefox, the subscription window pops up to view.

**Comment by Edwardsoen** [comment]
confirmed, will update next patch

**Comment by Edwardsoen** [comment]
v0.5.2 should fix this issue, it is up on Firefox add-on store, but chrome web store review will take a few days. 
if urgent, you can sideload from the 'releases' section on github, remember to disable the webstore version if you decide to do so.
