### ISSUE TITLE
Question asked in company not working with new chrome version

### ISSUE THREAD

**Issue by AgheraSachin** [Edwardsoen/Leetcode-Premium-Unlocker#63]
With the new version of leetcode & chrome, questions asked in the company not working.

![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/20219879/c4713a0a-602e-4bbe-a81b-3a3b224bc6d4)

**Comment by Edwardsoen** [comment]
Closing for duplicate issue https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/65
