### ISSUE TITLE
leetcode premium unlocker chrome site are not open 

### ISSUE THREAD

**Issue by swarnavopramanik** [Edwardsoen/Leetcode-Premium-Unlocker#72]
![Screenshot 2023-09-16 110456](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/105142693/4a7c755b-1732-4472-a816-9a343e0f4033)

**Comment by Edwardsoen** [comment]
Hi, please checkout this thread https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/67
