### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by navendra1707** [Edwardsoen/Leetcode-Premium-Unlocker#74]
The extension is not working on the leetcode site even after multiple refreshes.
![Screenshot (7)](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/131340062/396b66e5-5727-4137-8ef9-df2a4cc52d9b)

**Comment by Anubhab2003** [comment]
Exactly

**Comment by abanand132** [comment]
the extension is also removed from the chrome web store.

**Comment by Edwardsoen** [comment]
Hi, please check https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/67
