### ISSUE TITLE
Company function are dead

### ISSUE THREAD

**Issue by NawaNae** [Edwardsoen/Leetcode-Premium-Unlocker#8]
# As title
After click company link in all promblems page (https://leetcode.com/problemset/all/) will direct to subsribe page

**Comment by Edwardsoen** [comment]
Hi, which browser are you using? any screenshots ? does the frequency-unlocking work ?

**Comment by jaskaranl** [comment]
> Hi, which browser are you using? any screenshots ? does the frequency-unlocking work ?

it's basically happening across chrome on macos
and for frequency-unlocking method it works

**Comment by NawaNae** [comment]
> Hi, which browser are you using? any screenshots ? does the frequency-unlocking work ?

1. Hi I'm using MS edge on Windows11.
2. I think screenshot is quite similar to https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/9
3. yes, the frequency unlock is worked (the green bar)

And here I copy and save my html 
[htmls.zip](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/files/11411926/htmls.zip)

**Comment by Edwardsoen** [comment]
Thank you, will take a look

**Comment by Edwardsoen** [comment]
Current update: https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/10#issuecomment-1537216468 
closing the thread for duplicate issue, please comment there
