### ISSUE TITLE
Company Tags and editorial page is broken

### ISSUE THREAD

**Issue by SiddheshDhinge** [Edwardsoen/Leetcode-Premium-Unlocker#84]
In leetcode.com/problems/<question> the company tags unlocker and editorial unlocker are not working correctly. Looked through LC HTML source and found a hidden div that is catching all the class names used in the extension.

**Comment by Edwardsoen** [comment]
please check https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/67
