### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Divyanshbansal200** [Edwardsoen/Leetcode-Premium-Unlocker#87]
it is not working

**Comment by D-4-DIBAKAR** [comment]
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/71878062/d9394a51-9a5e-44f1-a5c8-eb82030db8f0)
 it is not working properly

**Comment by smith558** [comment]
As mentioned, stopped working completely.

**Comment by erickgtzh** [comment]
Is there a workaround or a way to make it work again?

**Comment by Edwardsoen** [comment]
please check https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/67
