### ISSUE TITLE
Bug in EXTENSION

### ISSUE THREAD

**Issue by Adithya4720** [Edwardsoen/Leetcode-Premium-Unlocker#88]
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/116452077/2311296c-5f47-40b2-b96c-28a753fbfd3a)

**Comment by Edwardsoen** [comment]
Hi, please check https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/issues/67
