### ISSUE TITLE
Outdated Excel

### ISSUE THREAD

**Issue by 31b4** [Edwardsoen/Leetcode-Premium-Unlocker#94]
Hi, can you update the excel database or, can you help me do it? Ive got premium but i dont know how to export the datas. @Edwardsoen

**Comment by Edwardsoen** [comment]
Hi, i used to use <a href ="https://github.com/Edwardsoen/LeetcodeScrapper"> this </a>  scraper, but it has become very unstable after they change the UI. i recommend writing your own scraper if you plan to update the data
